"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ORDER_STATUSES, statusLabel } from "../../lib/order-status";
import type { Order } from "../../lib/orders";

const empty = { customer_name:"", customer_phone:"", customer_email:"", equipment:"", issue:"", status:"received", public_note:"Equipo recibido. Pronto comenzaremos el diagnóstico.", internal_note:"" };
const date = (value: string) => new Intl.DateTimeFormat("es-AR", { dateStyle:"short", timeStyle:"short" }).format(new Date(value));

export default function AdminDashboard() {
  const [orders, setOrders] = useState<Order[]>([]); const [draft, setDraft] = useState(empty);
  const [filter, setFilter] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const router = useRouter();
  async function load() { const r = await fetch("/api/admin/orders", { cache:"no-store" }); if (r.status===401) return router.replace("/admin/login"); const data=await r.json(); setOrders(data.orders || []); if (!r.ok) setMessage(data.error); }
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => orders.filter(o => `${o.order_number} ${o.customer_name} ${o.equipment}`.toLowerCase().includes(filter.toLowerCase())), [orders, filter]);
  async function create(e: React.FormEvent) { e.preventDefault(); setBusy(true); setMessage(""); const r=await fetch("/api/admin/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)}); const data=await r.json(); setBusy(false); if(!r.ok)return setMessage(data.error); setDraft(empty); setMessage(`Orden #${data.order.order_number} creada correctamente.`); await load(); }
  async function save(order: Order) { setBusy(true); const r=await fetch(`/api/admin/orders/${order.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(order)}); const data=await r.json(); setBusy(false); setMessage(r.ok?`Orden #${order.order_number} actualizada.`:data.error); if(r.ok) await load(); }
  function edit(id:number, patch:Partial<Order>) { setOrders(current=>current.map(o=>o.id===id?{...o,...patch}:o)); }
  function whatsApp(order:Order) { const url=`${window.location.origin}/orden/${order.public_token}`; const text=`Hola ${order.customer_name}, tu orden TechPaws #${order.order_number} está: ${statusLabel(order.status)}.${order.public_note?`\n\n${order.public_note}`:""}\n\nPodés seguirla acá: ${url}\nCódigo de acceso: ${order.access_code}`; window.open(`https://wa.me/${order.customer_phone.replace(/\D/g,"")}?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer"); }
  async function logout(){ await fetch("/api/admin/logout",{method:"POST"}); router.replace("/admin/login"); router.refresh(); }
  return <main className="admin-shell"><header className="admin-header"><div><span>TECH<span>PAWS</span></span><small>ÓRDENES DE SERVICIO</small></div><div><a href="/seguimiento" target="_blank">Ver consulta pública ↗</a><button onClick={logout}>Salir</button></div></header>
    <section className="admin-intro"><div><p className="admin-kicker">PANEL PRIVADO</p><h1>Seguimiento claro,<br/>clientes tranquilos.</h1></div><div className="admin-stats"><div><strong>{orders.length}</strong><span>Órdenes</span></div><div><strong>{orders.filter(o=>o.status==="ready").length}</strong><span>Listas</span></div><div><strong>{orders.filter(o=>!['delivered','cancelled'].includes(o.status)).length}</strong><span>Activas</span></div></div></section>
    {message && <div className="admin-message">{message}</div>}
    <section className="admin-grid"><form className="order-create" onSubmit={create}><p className="admin-kicker">NUEVA ORDEN</p><h2>Registrar equipo</h2><div className="form-two"><label>Cliente *<input required value={draft.customer_name} onChange={e=>setDraft({...draft,customer_name:e.target.value})}/></label><label>WhatsApp *<input required placeholder="+54 11..." value={draft.customer_phone} onChange={e=>setDraft({...draft,customer_phone:e.target.value})}/></label></div><label>Email<input type="email" value={draft.customer_email} onChange={e=>setDraft({...draft,customer_email:e.target.value})}/></label><label>Equipo *<input required placeholder="Ej. Notebook Lenovo IdeaPad" value={draft.equipment} onChange={e=>setDraft({...draft,equipment:e.target.value})}/></label><label>Problema informado *<textarea required rows={3} value={draft.issue} onChange={e=>setDraft({...draft,issue:e.target.value})}/></label><label>Estado<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value})}>{ORDER_STATUSES.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></label><label>Mensaje visible para el cliente<textarea rows={3} value={draft.public_note} onChange={e=>setDraft({...draft,public_note:e.target.value})}/></label><label>Nota interna<textarea rows={2} value={draft.internal_note} onChange={e=>setDraft({...draft,internal_note:e.target.value})}/></label><button className="admin-primary" disabled={busy}>Crear orden</button></form>
      <div className="orders"><div className="orders-title"><div><p className="admin-kicker">ÓRDENES</p><h2>Trabajos registrados</h2></div><input aria-label="Buscar órdenes" placeholder="Buscar cliente, número o equipo" value={filter} onChange={e=>setFilter(e.target.value)}/></div><div className="order-list">{visible.map(order=><article className="order-card" key={order.id}><div className="order-top"><div><span className="order-number">#{order.order_number}</span><h3>{order.customer_name}</h3><p>{order.equipment} · {date(order.updated_at)}</p></div><span className={`status status-${order.status}`}>{statusLabel(order.status)}</span></div><p className="order-issue">{order.issue}</p><div className="order-edit"><label>Estado<select value={order.status} onChange={e=>edit(order.id,{status:e.target.value as Order["status"]})}>{ORDER_STATUSES.map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></label><label>Mensaje para el cliente<textarea rows={2} value={order.public_note||""} onChange={e=>edit(order.id,{public_note:e.target.value})}/></label><label>Nota interna<textarea rows={2} value={order.internal_note||""} onChange={e=>edit(order.id,{internal_note:e.target.value})}/></label></div><div className="order-meta"><span>Código: <strong>{order.access_code}</strong></span><a href={`/orden/${order.public_token}`} target="_blank">Ver seguimiento ↗</a></div><div className="order-actions"><button onClick={()=>save(order)} disabled={busy}>Guardar cambios</button><button className="wa-button" onClick={()=>whatsApp(order)}>Avisar por WhatsApp</button></div></article>)}{!visible.length&&<div className="empty-orders">Todavía no hay órdenes para mostrar.</div>}</div></div></section></main>;
}
